name: Build GKI

on:
  workflow_call:
    inputs:
      TODO:
        type: string
      VARIANT:
        type: string
      LAST_BUILD:
        type: string
      KERNEL_VERSION:
        type: string

  workflow_dispatch:
    inputs:
      TODO:
        description: To do
        default: "kernel"
        type: choice
        options:
          - "kernel"
          - "defconfig"
      VARIANT:
        description: kernel variants
        default: "KSU"
        type: choice
        options:
          - "VNL"
          - "KSU"
          - "KSUS"
      KERNEL_VERSION:
        description: Which kernel version do you want to build?
        default: "5.10"
        type: choice
        options:
          - "6.6"
          - "6.1"
          - "5.10"

env:
  MAN_DISABLE: true
  DEBIAN_FRONTEND: noninteractive
  GIT_CLONE_PROTECTION_ACTIVE: false
  #TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }} # telegram chat id
  #TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }} # telegram bot token
  GH_TOKEN: ${{ secrets.GH_TOKEN }} # github token
  VARIANT: ${{ inputs.VARIANT }}
  LAST_BUILD: ${{ inputs.LAST_BUILD }}
  TODO: ${{ inputs.TODO }}
  KVER: ${{ inputs.KERNEL_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Determine Build Status
        run: |
          if [ "${{ toJson(github.event.inputs) }}" == "null" ]; then
            echo "STATUS=RELEASE" >> $GITHUB_ENV
          else
            echo "STATUS=BETA" >> $GITHUB_ENV
          fi

#      - name: Validate Inputs and Secrets
#        run: |
#          _error() {
#              echo "❌ ERROR: $*"
#              let ret++
#          }

#          ret=0
#          # Check Secrets
#          if [[ -z "$TG_CHAT_ID" ]]; then
#            _error "Missing TG_CHAT_ID secret (Telegram Chat ID)"
#          fi
#          if [[ -z "$TG_BOT_TOKEN" ]]; then
#            _error "Missing TG_BOT_TOKEN secret (Telegram Bot Token)"
#          fi
#          if [[ -z "$GH_TOKEN" ]]; then
#            _error "Missing GH_TOKEN secret (GitHub PAT)"
#          fi

#          if [[ $ret -gt 0 ]]; then
#            exit $ret
#          fi

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gh bc bison flex libssl-dev libelf-dev dwarves cpio
          pip install lxml

      - name: Run Build Script
        run: |
          chmod +x *.sh py/*.py
          ./build.sh

      - name: Upload AnyKernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BASE_NAME }}-${{ github.run_number }}
          path: |
            artifacts/*.zip

      - name: Upload Info.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: info-${{ github.run_number }}
          path: artifacts/*.txt
